@ActindoMiddleware_HostAddress = http://localhost:5094

POST {{ActindoMiddleware_HostAddress}}/actindo/products/create
Content-Type: application/json

{
  "product": {
    "sku": "MASTER-SKU",
    "attributeSetId": 100,
    "variantStatus": "master",
    "inventory": [
      {
        "warehouseId": 1,
        "compartmentId": 1,
        "stock": 10
      }
    ],
    "variants": [
      {
        "sku": "MASTER-SKU-CHILD",
        "attributeSetId": 100,
        "variantStatus": "child",
        "inventory": [
          {
            "warehouseId": 1,
            "compartmentId": 1,
            "stock": 5
          }
        ]
      }
    ]
  }
}

###
